apache2
git-svn-id: https://svn.cac.washington.edu/svn/pubcookie/trunk@1147 b9756b1c-b508-4e7c-84e7-73dc1d0553b6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1097,29 +1097,29 @@ echo >confdefs.h
 
 # Predefined preprocessor variables.
 
-cat >>confdefs.h <<_ACEOF
-#define PACKAGE_NAME "$PACKAGE_NAME"
-_ACEOF
+# cat >>confdefs.h <<_ACEOF
+# #define PACKAGE_NAME "$PACKAGE_NAME"
+# _ACEOF
 
 
-cat >>confdefs.h <<_ACEOF
-#define PACKAGE_TARNAME "$PACKAGE_TARNAME"
-_ACEOF
+# cat >>confdefs.h <<_ACEOF
+# #define PACKAGE_TARNAME "$PACKAGE_TARNAME"
+# _ACEOF
 
 
-cat >>confdefs.h <<_ACEOF
-#define PACKAGE_VERSION "$PACKAGE_VERSION"
-_ACEOF
+# cat >>confdefs.h <<_ACEOF
+# #define PACKAGE_VERSION "$PACKAGE_VERSION"
+# _ACEOF
 
 
-cat >>confdefs.h <<_ACEOF
-#define PACKAGE_STRING "$PACKAGE_STRING"
-_ACEOF
+# cat >>confdefs.h <<_ACEOF
+# #define PACKAGE_STRING "$PACKAGE_STRING"
+# _ACEOF
 
 
-cat >>confdefs.h <<_ACEOF
-#define PACKAGE_BUGREPORT "$PACKAGE_BUGREPORT"
-_ACEOF
+# cat >>confdefs.h <<_ACEOF
+# #define PACKAGE_BUGREPORT "$PACKAGE_BUGREPORT"
+# _ACEOF
 
 
 # Let the site file select an alternate cache file if it wants to.
@@ -3528,9 +3528,9 @@ echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
 ( exit $ac_status )
 
-      { { echo "$as_me:$LINENO: error: Apache version 1.3.x is required!" >&5
-echo "$as_me: error: Apache version 1.3.x is required!" >&2;}
-   { (exit 1); exit 1; }; }
+#     { { echo "$as_me:$LINENO: error: Apache version 1.3.x is required!" >&5
+#cho "$as_me: error: Apache version 1.3.x is required!" >&2;}
+#  { (exit 1); exit 1; }; }
 
 
 fi
